//HintName: MyTests.SchedulePriceObjectType.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public enum SchedulePriceObjectType
{
    ADMISSION,
    PACKAGE,
    ATTRACTION,
}
