//HintName: MyTests.LiveShowTime.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class LiveShowTime
{
    [global::System.Text.Json.Serialization.JsonPropertyName("type")]
    public string Type { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("startTime")]
    public System.DateTimeOffset? StartTime { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("endTime")]
    public System.DateTimeOffset? EndTime { get; set; }

}
