//HintName: MyTests.LiveQueueBoardingGroup.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class LiveQueueBoardingGroup
{
    [global::System.Text.Json.Serialization.JsonPropertyName("allocationStatus")]
    public global::MyTests.BoardingGroupState AllocationStatus { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("currentGroupStart")]
    public double? CurrentGroupStart { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("currentGroupEnd")]
    public double? CurrentGroupEnd { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("nextAllocationTime")]
    public System.DateTimeOffset? NextAllocationTime { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("estimatedWait")]
    public double? EstimatedWait { get; set; }

}
