//HintName: MyTests.EntityChildLocation.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class EntityChildLocation
{
    [global::System.Text.Json.Serialization.JsonPropertyName("latitude")]
    public double? Latitude { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("longitude")]
    public double? Longitude { get; set; }

}
