//HintName: MyTests.EntityChildrenResponse.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class EntityChildrenResponse
{
    [global::System.Text.Json.Serialization.JsonPropertyName("id")]
    public string Id { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("name")]
    public string Name { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("entityType")]
    public global::MyTests.EntityType EntityType { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("timezone")]
    public string Timezone { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("children")]
    public global::System.Collections.Generic.List<global::MyTests.EntityChild> Children { get; set; }

}
