//HintName: MyTests.GetEntityScheduleYearMonth.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

[global::Shiny.Mediator.Http.HttpAttribute(global::Shiny.Mediator.Http.HttpVerb.Get, "/entity/{entityID}/schedule/{year}/{month}")]
public partial class GetEntityScheduleYearMonth : global::Shiny.Mediator.Http.IHttpRequest<global::MyTests.EntityScheduleResponse>
{
    [global::Shiny.Mediator.Http.HttpParameterAttribute(global::Shiny.Mediator.Http.HttpParameterType.Path, "entityID")]
    public string EntityID { get; set; }

    [global::Shiny.Mediator.Http.HttpParameterAttribute(global::Shiny.Mediator.Http.HttpParameterType.Path, "year")]
    public double Year { get; set; }

    [global::Shiny.Mediator.Http.HttpParameterAttribute(global::Shiny.Mediator.Http.HttpParameterType.Path, "month")]
    public double Month { get; set; }

}

