//HintName: MyTests.ReturnTimeState.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public enum ReturnTimeState
{
    AVAILABLE,
    TEMP_FULL,
    FINISHED,
}
