//HintName: MyTests.EntityScheduleResponse.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class EntityScheduleResponse
{
    [global::System.Text.Json.Serialization.JsonPropertyName("id")]
    public string Id { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("name")]
    public string Name { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("entityType")]
    public global::MyTests.EntityType EntityType { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("timezone")]
    public string Timezone { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("schedule")]
    public global::System.Collections.Generic.List<global::MyTests.ScheduleEntry> Schedule { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("parks")]
    public global::System.Collections.Generic.List<global::MyTests.EntityScheduleResponse> Parks { get; set; }

}
