//HintName: MyTests.ScheduleEntry.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class ScheduleEntry
{
    [global::System.Text.Json.Serialization.JsonPropertyName("date")]
    public string Date { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("openingTime")]
    public System.DateTimeOffset OpeningTime { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("closingTime")]
    public System.DateTimeOffset ClosingTime { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("type")]
    public ScheduleEntryType Type { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("purchases")]
    public global::System.Collections.Generic.List<global::MyTests.SchedulePriceObject> Purchases { get; set; }

}
