//HintName: MyTests.EntityLiveData.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class EntityLiveData
{
    [global::System.Text.Json.Serialization.JsonPropertyName("id")]
    public string Id { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("name")]
    public string Name { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("entityType")]
    public global::MyTests.EntityType EntityType { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("status")]
    public global::MyTests.LiveStatusType Status { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("lastUpdated")]
    public System.DateTimeOffset LastUpdated { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("queue")]
    public global::MyTests.LiveQueue Queue { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("showtimes")]
    public global::System.Collections.Generic.List<global::MyTests.LiveShowTime> Showtimes { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("operatingHours")]
    public global::System.Collections.Generic.List<global::MyTests.LiveShowTime> OperatingHours { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("diningAvailability")]
    public global::System.Collections.Generic.List<global::MyTests.DiningAvailability> DiningAvailability { get; set; }

}
