//HintName: MyTests.PriceData.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class PriceData
{
    [global::System.Text.Json.Serialization.JsonPropertyName("amount")]
    public double Amount { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("currency")]
    public string Currency { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("formatted")]
    public string Formatted { get; set; }

}
