//HintName: MyTests.LiveQueueSingleRider.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class LiveQueueSingleRider
{
    [global::System.Text.Json.Serialization.JsonPropertyName("waitTime")]
    public double? WaitTime { get; set; }

}
