//HintName: MyTests.TagData.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class TagData
{
    [global::System.Text.Json.Serialization.JsonPropertyName("tag")]
    public string Tag { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("tagName")]
    public string TagName { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("id")]
    public string Id { get; set; }

}
