//HintName: MyTests.GetEntityChildren.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

[global::Shiny.Mediator.Http.HttpAttribute(global::Shiny.Mediator.Http.HttpVerb.Get, "/entity/{entityID}/children")]
public partial class GetEntityChildren : global::Shiny.Mediator.Http.IHttpRequest<global::MyTests.EntityChildrenResponse>
{
    [global::Shiny.Mediator.Http.HttpParameterAttribute(global::Shiny.Mediator.Http.HttpParameterType.Path, "entityID")]
    public string EntityID { get; set; }

}

