//HintName: MyTests.ScheduleEntryType.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public enum ScheduleEntryType
{
    OPERATING,
    TICKETED_EVENT,
    PRIVATE_EVENT,
    EXTRA_HOURS,
    INFO,
}
