//HintName: MyTests.EntityChild.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class EntityChild
{
    [global::System.Text.Json.Serialization.JsonPropertyName("id")]
    public string Id { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("name")]
    public string Name { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("entityType")]
    public global::MyTests.EntityType EntityType { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("externalId")]
    public string ExternalId { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("parentId")]
    public string ParentId { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("location")]
    public EntityChildLocation Location { get; set; }

}
