//HintName: MyTests.SchedulePriceObject.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class SchedulePriceObject
{
    [global::System.Text.Json.Serialization.JsonPropertyName("type")]
    public SchedulePriceObjectType Type { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("id")]
    public string Id { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("name")]
    public string Name { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("price")]
    public global::MyTests.PriceData Price { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("available")]
    public bool Available { get; set; }

}
