//HintName: MyTests.LiveQueuePaidReturnTime.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class LiveQueuePaidReturnTime
{
    [global::System.Text.Json.Serialization.JsonPropertyName("state")]
    public global::MyTests.ReturnTimeState State { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("returnStart")]
    public System.DateTimeOffset? ReturnStart { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("returnEnd")]
    public System.DateTimeOffset? ReturnEnd { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("price")]
    public global::MyTests.PriceData Price { get; set; }

}
