//HintName: MyTests.DestinationsResponse.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class DestinationsResponse
{
    [global::System.Text.Json.Serialization.JsonPropertyName("destinations")]
    public global::System.Collections.Generic.List<global::MyTests.DestinationEntry> Destinations { get; set; }

}
