//HintName: MyTests.DestinationEntry.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class DestinationEntry
{
    [global::System.Text.Json.Serialization.JsonPropertyName("id")]
    public string Id { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("name")]
    public string Name { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("slug")]
    public string Slug { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("parks")]
    public global::System.Collections.Generic.List<global::MyTests.DestinationParkEntry> Parks { get; set; }

}
