//HintName: MyTests.DiningAvailability.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class DiningAvailability
{
    [global::System.Text.Json.Serialization.JsonPropertyName("partySize")]
    public double? PartySize { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("waitTime")]
    public double? WaitTime { get; set; }

}
