//HintName: MyTests.LiveQueue.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

public partial class LiveQueue
{
    [global::System.Text.Json.Serialization.JsonPropertyName("STANDBY")]
    public LiveQueueStandby Standby { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("SINGLE_RIDER")]
    public LiveQueueSingleRider SingleRider { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("RETURN_TIME")]
    public LiveQueueReturnTime ReturnTime { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("PAID_RETURN_TIME")]
    public LiveQueuePaidReturnTime PaidReturnTime { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("BOARDING_GROUP")]
    public LiveQueueBoardingGroup BoardingGroup { get; set; }

    [global::System.Text.Json.Serialization.JsonPropertyName("PAID_STANDBY")]
    public LiveQueuePaidStandby PaidStandby { get; set; }

}
