//HintName: MyTests.GetDestinations.g.cs
/// <summary>
/// This file is generated by Shiny.Mediator source generation
/// Do not modify this file directly
/// </summary>
#nullable enable

namespace MyTests;

[global::Shiny.Mediator.Http.HttpAttribute(global::Shiny.Mediator.Http.HttpVerb.Get, "/destinations")]
public partial class GetDestinations : global::Shiny.Mediator.Http.IHttpRequest<global::MyTests.DestinationsResponse>
{
}

