<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Shiny.Mediator</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Mediator.Contracts.SourceGenerators\Shiny.Mediator.Contracts.SourceGenerators.csproj"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

    <PropertyGroup>
        <SourceGenBinDir>..\Shiny.Mediator.Contracts.SourceGenerators\bin\$(Configuration)\netstandard2.0</SourceGenBinDir>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(SourceGenBinDir)\Shiny.Mediator.Contracts.SourceGenerators.dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false" />
    </ItemGroup>
</Project>
