using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Shiny.Mediator.SourceGenerators;

/// <summary>
/// Reusable code generator for HTTP request handlers
/// </summary>
public static class HttpHandlerCodeGenerator
{
    public static string GenerateHandler(
        string handlerClassName,
        string requestTypeFullName,
        string resultTypeFullName,
        bool isStreamRequest,
        string httpMethod,
        string route,
        IEnumerable<HttpPropertyInfo> properties,
        bool implementsServerSentEvents,
        string targetNamespace
    )
    {
        // Materialize the properties once to avoid multiple enumeration
        var propertiesList = properties.ToList();
        
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Code generated by Shiny Mediator HTTP Client Source Generator.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        
        if (isStreamRequest)
        {
            sb.AppendLine("using System.Collections.Generic;");
        }
        
        sb.AppendLine();
        sb.AppendLine($"namespace {targetNamespace};");
        sb.AppendLine();
        sb.AppendLine(Constants.GeneratedCodeAttributeString);

        if (isStreamRequest)
        {
            sb.AppendLine($"public partial class {handlerClassName}(global::Shiny.Mediator.Http.HttpHandlerServices services)");
            sb.AppendLine($"    : global::Shiny.Mediator.Http.BaseHttpRequestHandler(services),");
            sb.AppendLine($"      global::Shiny.Mediator.IStreamRequestHandler<{requestTypeFullName}, {resultTypeFullName}>");
            sb.AppendLine("{");
            sb.AppendLine($"    public global::System.Collections.Generic.IAsyncEnumerable<{resultTypeFullName}> Handle(");
            sb.AppendLine($"        {requestTypeFullName} request,");
            sb.AppendLine($"        global::Shiny.Mediator.IMediatorContext context,");
            sb.AppendLine($"        global::System.Threading.CancellationToken cancellationToken)");
            sb.AppendLine("    {");
        }
        else
        {
            sb.AppendLine($"public partial class {handlerClassName}(global::Shiny.Mediator.Http.HttpHandlerServices services)");
            sb.AppendLine($"    : global::Shiny.Mediator.Http.BaseHttpRequestHandler(services),");
            sb.AppendLine($"      global::Shiny.Mediator.IRequestHandler<{requestTypeFullName}, {resultTypeFullName}>");
            sb.AppendLine("{");
            sb.AppendLine($"    public global::System.Threading.Tasks.Task<{resultTypeFullName}> Handle(");
            sb.AppendLine($"        {requestTypeFullName} request,");
            sb.AppendLine($"        global::Shiny.Mediator.IMediatorContext context,");
            sb.AppendLine($"        global::System.Threading.CancellationToken cancellationToken)");
            sb.AppendLine("    {");
        }

        // Build the route with parameters
        var processedRoute = ProcessRoute(route, propertiesList);
        sb.AppendLine($"        var route = {processedRoute};");
        
        // Create HTTP request message
        var httpMethodMapping = GetHttpMethodMapping(httpMethod);
        sb.AppendLine($"        var httpRequest = new global::System.Net.Http.HttpRequestMessage({httpMethodMapping}, route);");
        sb.AppendLine();

        // Add headers
        var headerProps = propertiesList.Where(p => p.ParameterType == HttpParameterType.Header).ToList();
        foreach (var prop in headerProps)
        {
            sb.AppendLine($"        if (request.{prop.PropertyName} != null)");
            sb.AppendLine($"            httpRequest.Headers.Add(\"{prop.ParameterName}\", request.{prop.PropertyName}.ToString());");
            sb.AppendLine();
        }

        // Add body
        var bodyProp = propertiesList.FirstOrDefault(p => p.ParameterType == HttpParameterType.Body);
        if (bodyProp != null)
        {
            sb.AppendLine($"        if (request.{bodyProp.PropertyName} != null)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var json = services.Serializer.Serialize(request.{bodyProp.PropertyName});");
            sb.AppendLine("            httpRequest.Content = new global::System.Net.Http.StringContent(json, global::System.Text.Encoding.UTF8, \"application/json\");");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // Call base handler method
        if (isStreamRequest)
        {
            var useSse = implementsServerSentEvents ? "true" : "request is global::Shiny.Mediator.Http.IServerSentEventsStream";
            sb.AppendLine($"        return this.HandleStream<{requestTypeFullName}, {resultTypeFullName}>(");
            sb.AppendLine("            httpRequest,");
            sb.AppendLine("            request,");
            sb.AppendLine($"            {useSse},");
            sb.AppendLine("            context,");
            sb.AppendLine("            cancellationToken");
            sb.AppendLine("        );");
        }
        else
        {
            sb.AppendLine($"        return this.HandleRequest<{requestTypeFullName}, {resultTypeFullName}>(");
            sb.AppendLine("            httpRequest,");
            sb.AppendLine("            request,");
            sb.AppendLine("            context,");
            sb.AppendLine("            cancellationToken");
            sb.AppendLine("        );");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string GenerateRegistration(
        IEnumerable<HandlerRegistrationInfo> handlers,
        string targetNamespace
    )
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Code generated by Shiny Mediator HTTP Client Source Generator.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {targetNamespace};");
        sb.AppendLine();
        sb.AppendLine(Constants.GeneratedCodeAttributeString);
        sb.AppendLine("public static class __ShinyHttpClientRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddHttpHandlers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var handler in handlers)
        {
            if (handler.IsStreamRequest)
            {
                sb.AppendLine($"        services.TryAddSingleton<global::Shiny.Mediator.IStreamRequestHandler<{handler.RequestTypeFullName}, {handler.ResultTypeFullName}>, {handler.HandlerTypeFullName}>();");
            }
            else
            {
                sb.AppendLine($"        services.TryAddSingleton<global::Shiny.Mediator.IRequestHandler<{handler.RequestTypeFullName}, {handler.ResultTypeFullName}>, {handler.HandlerTypeFullName}>();");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ProcessRoute(string route, IEnumerable<HttpPropertyInfo> properties)
    {
        // Materialize once to avoid multiple enumeration
        var propertiesList = properties.ToList();
        
        // Check if route contains any interpolation markers
        var hasParameters = route.Contains("{") || propertiesList.Any(p => p.ParameterType == HttpParameterType.Query);

        if (!hasParameters)
        {
            return $"\"{route}\"";
        }

        var result = route;
        var queryParams = new List<string>();

        foreach (var prop in propertiesList)
        {
            if (prop.ParameterType == HttpParameterType.Path)
            {
                // Route parameter - use direct interpolation
                var routeParam = $"{{{prop.ParameterName}}}";
                if (result.Contains(routeParam))
                {
                    result = result.Replace(routeParam, $"{{request.{prop.PropertyName}}}");
                }
            }
            else if (prop.ParameterType == HttpParameterType.Query)
            {
                // Query parameter - add to query string
                queryParams.Add($"{prop.ParameterName}={{global::System.Uri.EscapeDataString(request.{prop.PropertyName}?.ToString() ?? \"\")}}");
            }
        }

        // Add query parameters to route
        if (queryParams.Count > 0)
        {
            var separator = result.Contains("?") ? "&" : "?";
            result = result + separator + string.Join("&", queryParams);
        }

        return $"$\"{result}\"";
    }

    private static string GetHttpMethodMapping(string httpMethod)
    {
        return httpMethod switch
        {
            "Get" or "GET" => "global::System.Net.Http.HttpMethod.Get",
            "Post" or "POST" => "global::System.Net.Http.HttpMethod.Post",
            "Put" or "PUT" => "global::System.Net.Http.HttpMethod.Put",
            "Patch" or "PATCH" => "global::System.Net.Http.HttpMethod.Patch",
            "Delete" or "DELETE" => "global::System.Net.Http.HttpMethod.Delete",
            _ => "global::System.Net.Http.HttpMethod.Get"
        };
    }
}

public enum HttpParameterType
{
    Path,
    Query,
    Header,
    Body
}

public record HttpPropertyInfo(
    string PropertyName,
    string ParameterName,
    HttpParameterType ParameterType
);

public record HandlerRegistrationInfo(
    string HandlerTypeFullName,
    string RequestTypeFullName,
    string ResultTypeFullName,
    bool IsStreamRequest
);

