name: Feature Request
description: You have an idea for an enhancement within Shiny Mediator
title: "[Feature Request]: "
labels: [feature request, unverified]
body:
  - type: textarea
    attributes:
      label: Summary
      description: Your summary of the feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: API Changes
    validations:
      required: true
  - type: textarea
    attributes:
      label: Intended Use Case
    validations:
      required: true
