//HintName: TestAssembly_Extensions.g.cs
// <auto-generated>
// Code generated by Shiny Mediator Source Generator.
// </auto-generated>
#nullable disable

using Microsoft.Extensions.DependencyInjection;

namespace TestAssembly;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Shiny.Mediator.SourceGenerators", "4.0.0")]
public static class __ShinyMediatorSourceGenExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDiscoveredMediatorHandlersFromTestAssembly(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddSingletonAsImplementedInterfaces<global::MyApp.Handler1>();
        services.AddScopedAsImplementedInterfaces<global::MyApp.Handler2>();
        services.AddSingletonAsImplementedInterfaces<global::MyApp.StreamHandler1>();

        services.AddSingleton<global::Shiny.Mediator.Infrastructure.IRequestExecutor, TestAssembly.TestAssemblyRequestExecutor>();
        services.AddSingleton<global::Shiny.Mediator.Infrastructure.IStreamRequestExecutor, TestAssembly.TestAssemblyStreamRequestExecutor>();

        return services;
    }
}
