//HintName: MyApp_Extensions.g.cs
// <auto-generated>
// Code generated by Shiny Mediator Source Generator.
// </auto-generated>
#nullable disable

using Microsoft.Extensions.DependencyInjection;
using Shiny.Mediator;

namespace MyApp;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Shiny.Mediator.SourceGenerators", "5.0.0")]
public static class __ShinyMediatorSourceGenExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDiscoveredMediatorHandlersFromMyApp(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddSingletonAsImplementedInterfaces<global::MyApp.MyHandler>();

        services.AddSingleton<global::Shiny.Mediator.Infrastructure.IRequestExecutor, global::MyApp.MyCustomRequestExecutor>();

        return services;
    }
}
