//HintName: MyCompanyMyProductFeatures_Extensions.g.cs
// <auto-generated>
// Code generated by Shiny Mediator Source Generator.
// </auto-generated>
#nullable disable

using Microsoft.Extensions.DependencyInjection;
using Shiny.Mediator;

namespace MyCompany.MyProduct.Features;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Shiny.Mediator.SourceGenerators", "5.0.0")]
public static class MediatorServiceExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDiscoveredMediatorHandlersFromMyCompanyMyProductFeatures(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddSingletonAsImplementedInterfaces<global::MyCompany.MyProduct.Features.MyRequestHandler>();
        services.AddSingletonAsImplementedInterfaces<global::MyCompany.MyProduct.Features.MyStreamHandler>();

        services.AddSingleton<global::Shiny.Mediator.Infrastructure.IRequestExecutor, global::MyCompany.MyProduct.Features.CustomRequestExec>();
        services.AddSingleton<global::Shiny.Mediator.Infrastructure.IStreamRequestExecutor, global::MyCompany.MyProduct.Features.CustomStreamExec>();

        return services;
    }
}
