//HintName: TestAssembly_Extensions.g.cs
// <auto-generated>
// Code generated by Shiny Mediator Source Generator.
// </auto-generated>
#nullable disable

using Microsoft.Extensions.DependencyInjection;
using Shiny.Mediator;

namespace TestAssembly;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Shiny.Mediator.SourceGenerators", "5.0.0")]
public static class __ShinyMediatorSourceGenExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDiscoveredMediatorHandlersFromTestAssembly(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddSingletonAsImplementedInterfaces<global::MyApp.MyRequestHandler>();
        services.AddScopedAsImplementedInterfaces<global::MyApp.MyCommandHandler>();

        services.AddSingleton(typeof(global::Shiny.Mediator.IRequestMiddleware<,>), typeof(global::MyApp.LoggingRequestMiddleware<,>));
        services.AddScoped(typeof(global::Shiny.Mediator.ICommandMiddleware<>), typeof(global::MyApp.ValidationCommandMiddleware<>));

        services.AddSingleton<global::Shiny.Mediator.Infrastructure.IRequestExecutor, global::TestAssembly.TestAssemblyRequestExecutor>();

        return services;
    }
}
