//HintName: TestAssembly_Extensions.g.cs
// <auto-generated>
// Code generated by Shiny Mediator Source Generator.
// </auto-generated>
#nullable disable

using Microsoft.Extensions.DependencyInjection;
using Shiny.Mediator;

namespace TestAssembly;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Shiny.Mediator.SourceGenerators", "5.0.0")]
public static class __ShinyMediatorSourceGenExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDiscoveredMediatorHandlersFromTestAssembly(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddScopedAsImplementedInterfaces<global::MyApp.ComplexHandlers.UserHandler>();

        services.AddSingleton<global::Shiny.Mediator.Infrastructure.IRequestExecutor, TestAssembly.TestAssemblyRequestExecutor>();
        services.AddSingleton<global::Shiny.Mediator.Infrastructure.IStreamRequestExecutor, TestAssembly.TestAssemblyStreamRequestExecutor>();

        return services;
    }
}
