//HintName: MainApp_Registry.g.cs
// <auto-generated>
// Code generated by Shiny Mediator Source Generator.
// </auto-generated>
#nullable disable

using Shiny.Mediator;
using Microsoft.Extensions.DependencyInjection;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Shiny.Mediator.SourceGenerators", "5.0.0")]
internal static class __ShinyMediatorRegistryFromReferences
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    public static void Run()
    {
        global::Shiny.Mediator.Infrastructure.MediatorRegistry.RegisterCallback(builder =>
        {
         builder.Services.AddSingletonAsImplementedInterfaces<global::MainApp.MainRequestHandler>();
         builder.Services.AddSingletonAsImplementedInterfaces<global::Project1.Handlers.Project1RequestHandler>();
         builder.Services.AddScopedAsImplementedInterfaces<global::Project1.Handlers.Project1CommandHandler>();
         builder.Services.AddScopedAsImplementedInterfaces<global::Project2.Features.Project2RequestHandler>();
         builder.Services.AddSingletonAsImplementedInterfaces<global::Project2.Features.Project2StreamHandler>();
         builder.Services.AddScopedAsImplementedInterfaces<global::Project2.Features.Project2EventHandler>();

         builder.Services.AddSingleton(typeof(global::Shiny.Mediator.IRequestMiddleware<,>), typeof(global::Project1.Handlers.Project1RequestMiddleware<,>));
         builder.Services.AddSingleton(typeof(global::Shiny.Mediator.ICommandMiddleware<>), typeof(global::Project2.Features.Project2CommandMiddleware<>));

    builder.Services.AddSingleton<global::Shiny.Mediator.Infrastructure.IRequestExecutor, global::MainApp.MainAppRequestExecutor>();
   builder.Services.AddSingleton<global::Shiny.Mediator.Infrastructure.IStreamRequestExecutor, global::MainApp.MainAppStreamRequestExecutor>();
        });
    }
}
