//HintName: MyApp_StreamRequestExecutor.g.cs
// <auto-generated>
// Code generated by Shiny Mediator Source Generator.
// </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using System.Threading;

namespace MyApp;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Shiny.Mediator.SourceGenerators", "5.0.0")]
internal class MyCustomStreamExecutor : global::Shiny.Mediator.Infrastructure.StreamRequestExecutor
{
    public override global::System.Collections.Generic.IAsyncEnumerable<TResult> Request<TResult>(
        global::Shiny.Mediator.IMediatorContext context,
        global::Shiny.Mediator.IStreamRequest<TResult> request,
        global::System.Threading.CancellationToken cancellationToken)
    {
        if (request is global::MyApp.MyStreamRequest p0)
        {
            var handle = this.Execute<global::MyApp.MyStreamRequest, string>(context, p0, cancellationToken);
            return (global::System.Collections.Generic.IAsyncEnumerable<TResult>)handle;
        }

        throw new global::System.InvalidOperationException("Unknown request type");
    }

    public override bool CanRequest<TResult>(global::Shiny.Mediator.IStreamRequest<TResult> request)
    {
        if (request is global::MyApp.MyStreamRequest)
            return true;

        return false;
    }
}
