<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <ShinyMediatorGenerateAITools>true</ShinyMediatorGenerateAITools>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Shiny.Mediator\Shiny.Mediator.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Mediator.SourceGenerators\Shiny.Mediator.SourceGenerators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.AI"/>
        <PackageReference Include="Microsoft.Extensions.AI.OpenAI"/>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
    </ItemGroup>
    <Import Project="..\..\src\Shiny.Mediator.SourceGenerators\SourceGenerators.targets"/>
</Project>
