using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Readers;

namespace Shiny.Mediator.SourceGenerators.Http;


public class OpenApiContractGenerator(MediatorHttpItemConfig itemConfig, Action<string> output)
{

    public string Generate(Stream stream)
    {
        using var streamReader = new StreamReader(stream);
        var reader = new OpenApiStreamReader();
        var document = reader.Read(streamReader.BaseStream, out var diagnostic);
        if (document == null)
            throw new InvalidOperationException("OpenApi Document is null");
        
        if (diagnostic.Errors != null && diagnostic.Errors.Count > 0)
        {
            var e = diagnostic.Errors.First();
            throw new InvalidOperationException($"OpenApi Error: {e.Message} - {e.Pointer}");
        }
        
        var sb = new StringBuilder();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// This file is generated by Shiny.Mediator source generation");
        sb.AppendLine("/// Do not modify this file directly");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"namespace {itemConfig.Namespace};");
        sb.AppendLine();
        
        GenerateComponents(sb, document, itemConfig, output);
        GenerateContracts(sb, document, itemConfig, output);

        return sb.ToString();
    }


    void GenerateComponents(StringBuilder sb, OpenApiDocument document, MediatorHttpItemConfig itemConfig, Action<string> output)
    {
        output("Generating Components for " + itemConfig.Namespace);
        foreach (var schema in document.Components.Schemas)
        {
            var type = GenerateComplexType(schema, output);
            if (type == null)
                throw new InvalidOperationException("Invalid Schema Type");

            sb.Append(type);
            sb.AppendLine();
        }
    }


    void GenerateContracts(StringBuilder sb, OpenApiDocument document, MediatorHttpItemConfig itemConfig, Action<string> output)
    {
        foreach (var path in document.Paths)
        {
            output("PATH: " + path.Key);
            
            foreach (var op in path.Value.Operations)
            {
                if (String.IsNullOrWhiteSpace(op.Value.OperationId))
                {
                    output("NO OPERATION ID on " + op.Key);
                    continue;
                }
                output($"OPERATION: {op.Key} - ID: {op.Value.OperationId}");
                var responseType = this.GetResponseType(op.Value);
                output($"RESPONSE: {responseType}");
                
                var contractName = $"{itemConfig.ContractPrefix}{op.Value.OperationId.Pascalize()}{itemConfig.ContractPostfix}";
                var httpMethod = op.Key.ToString();
                
                sb.AppendLine($"[global::Shiny.Mediator.Http.HttpAttribute(global::Shiny.Mediator.Http.HttpVerb.{httpMethod}, \"{path.Key}\")]");
                sb.AppendLine($"public partial class {contractName} : global::Shiny.Mediator.Http.IHttpRequest<{responseType}>");
                sb.AppendLine("{");
                
                foreach (var parameter in op.Value.Parameters)
                {
                    var argType = parameter.In == ParameterLocation.Path ? "Path" : "Query";
                    var typeName = this.GetSchemaType(parameter.Schema);
                    var propertyName = parameter.Name.Pascalize();
                    sb.AppendLine($"    [global::Shiny.Mediator.Http.HttpParameter(global::Shiny.Mediator.Http.HttpParameterType.{argType})]");
                    sb.AppendLine($"    public {typeName} {propertyName} {{ get; set; }}");
                    sb.AppendLine();
                    output($"PROPERTY: {propertyName} ({typeName} - {argType})");
                }

                if (op.Value.RequestBody != null)
                {
                    var body = op.Value.RequestBody;
                    var bodyResponseType = this.GetApplicationJsonResponse(body.Content);
                    if (bodyResponseType != null)
                    {
                        if (!body.Required)
                            bodyResponseType += "?";
                        
                        sb.AppendLine($"    [global::Shiny.Mediator.Http.HttpParameter(global::Shiny.Mediator.Http.HttpParameterType.Body)]");
                        sb.AppendLine($"    public {bodyResponseType} Body {{ get; set; }}");
                        output("BODY: " + bodyResponseType);
                    }
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }
    }
    

    string GetResponseType(OpenApiOperation op)
    {
        var responseType = "global::Shiny.Mediator.Unit";
        if (op.Responses.TryGetValue("200", out var response200))
        {
            var appJsonType = this.GetApplicationJsonResponse(response200.Content);
            if (appJsonType != null)
                responseType = appJsonType;
        }

        return responseType;
    }
    

    string? GetApplicationJsonResponse(IDictionary<string, OpenApiMediaType> response)
    {
        string? responseType = null;
        if (response.TryGetValue("application/json", out var responseContent))
            responseType = this.GetSchemaType(responseContent.Schema);

        return responseType;
    }


    string? GetSchemaType(OpenApiSchema schema)
    {
        string type = null!;
        if (schema.Type != null)
        {
            switch (schema.Type)
            {
                case "string":
                    if (schema.Enum.Count > 0)
                        type = $"global::{itemConfig.Namespace}.{schema.Reference.Id}";
                    else
                        type = GetStringType(schema);
                    break;

                case "integer":
                case "number":
                    type = GetNumberType(schema.Format);
                    break;

                case "boolean":
                    type = "bool";
                    break;

                case "array":
                    var listType = this.GetSchemaType(schema.Items);
                    return $"global::System.Collections.Generic.List<{listType}>";

                case "file":
                    return "global::System.IO.Stream";
                
                case "object":
                    if (schema.AdditionalProperties == null)
                    {
                        type = $"global::{itemConfig.Namespace}.{schema.Reference.Id}";    
                    }
                    else
                    {
                        var dictionaryValueType = this.GetSchemaType(schema.AdditionalProperties);
                        type = $"global::System.Collections.Generic.Dictionary<string, {dictionaryValueType}>";
                    }
                    break;

                default:
                    throw new InvalidOperationException("Invalid type - " + schema.Type);
            }
        }
        // TODO: we're not ready for more than 1 right now
        else if ((schema.AllOf?.Count ?? 0) == 1)
        {
            // if discriminator is present, 2 will come through which means the following will error
            // we want to return null instead
            type = this.GetSchemaType(schema.AllOf!.Single()!)!;
        }
        else
        {
            return null;
        }

        if (schema.Nullable)
            type += "?";
        
        return type;
    }
    
    static string GetStringType(OpenApiSchema schema) => schema.Type switch
    {
        "date-time" => "System.DateTimeOffset",
        "uuid" => "System.Guid",
        "date" => "System.DateOnly",
        "time" => "System.TimeOnly",
        // "binary" => "byte[]",
        // "file" => "",
        _ => "string"
    };

    static string GetNumberType(string format) => format switch
    {
        "int32" => "int",
        "int64" => "long",
        "float" => "float",
        "double" => "double",
        _ => throw new InvalidOperationException("Invalid Number Format - " + format)
    };
    
    string GenerateComplexType(KeyValuePair<string, OpenApiSchema> schema, Action<string> output)
    {
        output("COMPONENT: " + schema.Key);
        var sb = new StringBuilder();
        var className = schema.Key.Pascalize();

        if (schema.Value.Enum.Count > 0)
        {
            output("ENUM COMPONENT GENERATING");
            sb.AppendLine($"public enum {className}");
            sb.AppendLine("{");
            foreach (var ev in schema.Value.Enum.OfType<OpenApiString>())
            {
                sb.AppendLine($"    {ev.Value},");
            }
            sb.AppendLine("}");
        }
        else
        {
            output("GENERATING CLASS COMPONENT");
            sb.Append("public partial class " + className);

            // TODO: this will be 2 when discriminators are present
            //if (schema.Value.AllOf.Count > 1)
            //{
            //    Debugger.Launch();
            //}

            if (schema.Value.AllOf.Count == 1)
            {
                // add inheritance
                var baseType = this.GetSchemaType(schema.Value.AllOf.Single());
                sb.AppendLine($" : {baseType}");

                output($"INHERITED: {className} ({baseType})");
            }
            sb.AppendLine();
            sb.AppendLine("{");
            
            foreach (var prop in schema.Value.Properties)
            {
                var propertyName = prop.Key.Pascalize();
                if (prop.Value != null)
                {
                    var typeName = this.GetSchemaType(prop.Value);
                    sb.AppendLine($"    [System.Text.Json.Serialization.JsonPropertyName(\"{prop.Key}\")]");
                    sb.AppendLine( "    public " + typeName + " " + propertyName + " { get; set; }");
                    sb.AppendLine();
                    
                    output($"PROPERTY: {propertyName} ({typeName})");
                }
            }
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
