using System.ComponentModel.DataAnnotations;
using Shiny.AppFunctions;

namespace Shiny.Mediator.Tests;


// The Shiny.AppFunctions generator runs over this project (it flows from Shiny.Mediator.AppFunctions), so these tests
// go through the same generated registry + AppFunctionDispatcher pipeline that Siri and Android agents use.
public class AppFunctionsTests
{
    readonly IServiceProvider services;
    readonly AppFunctionDispatcher dispatcher;


    public AppFunctionsTests()
    {
        var sc = new ServiceCollection();
        sc.AddLogging();
        sc.AddShinyMediator(cfg =>
        {
            cfg.AddDataAnnotations();
            cfg.AddOpenRequestMiddleware(typeof(AppFunctionTrackingMiddleware<,>));
        }, false);

        sc.AddSingleton<AppFunctionCallTracker>();
        sc.AddScoped<IRequestHandler<AfGreetRequest, string>, AfGreetRequestHandler>();
        sc.AddScoped<IRequestHandler<AfValidatedRequest, int>, AfValidatedRequestHandler>();
        sc.AddScoped<ICommandHandler<AfRecordCommand>, AfRecordCommandHandler>();
        sc.AddAppFunctions(); // generated by Shiny.AppFunctions

        this.services = sc.BuildServiceProvider();
        this.dispatcher = this.services.GetRequiredService<AppFunctionDispatcher>();
    }


    [Fact]
    public void Functions_Registered()
    {
        var ids = this.dispatcher.Registry.Functions.Select(x => x.Id).ToList();
        ids.ShouldContain("af_greet");
        ids.ShouldContain("af_validated");
        ids.ShouldContain("af_record");
    }


    [Fact]
    public async Task Request_RunsThroughMediatorPipeline()
    {
        var outcome = await this.dispatcher.Execute(
            new AppFunctionInvocation("af_greet", AppFunctionPlatform.Apple),
            """{"name":"Allan","mood":"Happy"}""",
            CancellationToken.None
        );

        outcome.Status.ShouldBe(AppFunctionStatus.Success, outcome.Message);
        outcome.ResultJson.ShouldBe("\"Hello Allan (Happy) from Apple\"");
        outcome.Dialog.ShouldBe("Said hello to Allan");

        var tracker = this.services.GetRequiredService<AppFunctionCallTracker>();
        tracker.MiddlewareSawFunctionIds.ShouldContain("af_greet");
    }


    [Fact]
    public async Task Command_RunsThroughMediator()
    {
        var outcome = await this.dispatcher.Execute(
            new AppFunctionInvocation("af_record", AppFunctionPlatform.Android, CallerPackage: "com.google.gemini"),
            """{"value":"test"}""",
            CancellationToken.None
        );

        outcome.Status.ShouldBe(AppFunctionStatus.Success, outcome.Message);
        outcome.ResultJson.ShouldBeNull();

        var tracker = this.services.GetRequiredService<AppFunctionCallTracker>();
        tracker.RecordedValues.ShouldContain("test|com.google.gemini");
    }


    [Fact]
    public async Task ValidateException_BecomesInvalidArgument()
    {
        var outcome = await this.dispatcher.Execute(
            new AppFunctionInvocation("af_validated"),
            """{"quantity":5}""",
            CancellationToken.None
        );

        outcome.Status.ShouldBe(AppFunctionStatus.Error);
        outcome.ErrorCode.ShouldBe(AppFunctionErrorCode.InvalidArgument);
        outcome.Message.ShouldBe("Name is required");
    }


    [Fact]
    public async Task ValidateException_Range_BecomesInvalidArgument()
    {
        var outcome = await this.dispatcher.Execute(
            new AppFunctionInvocation("af_validated"),
            """{"quantity":500,"name":"Allan"}""",
            CancellationToken.None
        );

        outcome.Status.ShouldBe(AppFunctionStatus.Error);
        outcome.ErrorCode.ShouldBe(AppFunctionErrorCode.InvalidArgument);
        outcome.Message.ShouldBe("Quantity must be between 1 and 10");
    }


    [Fact]
    public async Task AppFunctionException_FromHandler_PassesThrough()
    {
        var outcome = await this.dispatcher.Execute(
            new AppFunctionInvocation("af_greet"),
            """{"name":"nobody","mood":"Sad"}""",
            CancellationToken.None
        );

        outcome.Status.ShouldBe(AppFunctionStatus.Error);
        outcome.ErrorCode.ShouldBe(AppFunctionErrorCode.NotFound);
        outcome.Message.ShouldBe("Nobody to greet");
    }


    [Fact]
    public async Task DirectMediatorCall_HasNoAppFunctionContext()
    {
        var mediator = this.services.GetRequiredService<IMediator>();
        var (_, result) = await mediator.Request(new AfGreetRequest("Allan", AfMood.Happy));

        result.ShouldBe("Hello Allan (Happy) from mediator");
        this.services.GetRequiredService<AppFunctionCallTracker>().MiddlewareSawFunctionIds.ShouldBeEmpty();
    }
}


public enum AfMood { Happy, Sad }


[AppFunction("af_greet", Description = "Greets someone")]
public record AfGreetRequest(string Name, AfMood Mood) : IAppFunctionRequest<string>;

public class AfGreetRequestHandler : IAppFunctionRequestHandler<AfGreetRequest, string>
{
    public Task<string> Handle(AfGreetRequest request, IMediatorContext context, CancellationToken cancellationToken)
    {
        if (request.Name == "nobody")
            throw new AppFunctionException(AppFunctionErrorCode.NotFound, "Nobody to greet");

        var from = context.GetAppFunctionContext()?.Platform.ToString() ?? "mediator";
        context.SayToAssistant($"Said hello to {request.Name}");
        return Task.FromResult($"Hello {request.Name} ({request.Mood}) from {from}");
    }
}


[Validate]
[AppFunction("af_validated", Description = "Validated with data annotations")]
public class AfValidatedRequest : IAppFunctionRequest<int>
{
    [Range(1, 10, ErrorMessage = "Quantity must be between 1 and 10")]
    public int Quantity { get; set; }

    [Required(ErrorMessage = "Name is required")]
    public string? Name { get; set; }
}

public class AfValidatedRequestHandler : IAppFunctionRequestHandler<AfValidatedRequest, int>
{
    public Task<int> Handle(AfValidatedRequest request, IMediatorContext context, CancellationToken cancellationToken)
        => Task.FromResult(request.Quantity);
}


[AppFunction("af_record", Description = "Records a value")]
public record AfRecordCommand(string Value) : IAppFunctionCommand;

public class AfRecordCommandHandler(AppFunctionCallTracker tracker) : IAppFunctionCommandHandler<AfRecordCommand>
{
    public Task Handle(AfRecordCommand command, IMediatorContext context, CancellationToken cancellationToken)
    {
        tracker.RecordedValues.Add($"{command.Value}|{context.GetAppFunctionContext()?.CallerPackage}");
        return Task.CompletedTask;
    }
}


public class AppFunctionCallTracker
{
    public List<string> MiddlewareSawFunctionIds { get; } = new();
    public List<string> RecordedValues { get; } = new();
}

public class AppFunctionTrackingMiddleware<TRequest, TResult>(AppFunctionCallTracker tracker) : IRequestMiddleware<TRequest, TResult>
    where TRequest : IRequest<TResult>
{
    public Task<TResult> Process(IMediatorContext context, RequestHandlerDelegate<TResult> next, CancellationToken cancellationToken)
    {
        var afc = context.GetAppFunctionContext();
        if (afc != null)
            tracker.MiddlewareSawFunctionIds.Add(afc.FunctionId);

        return next();
    }
}
