<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Shiny.Mediator</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Mediator\Shiny.Mediator.csproj"/>
        <ProjectReference Include="..\Shiny.Mediator.AspNet.SourceGenerators\Shiny.Mediator.AspNet.SourceGenerators.csproj"
                          ReferenceOutputAssembly="false" />
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\Shiny.Mediator.AspNet.SourceGenerators\bin\$(Configuration)\netstandard2.0\Shiny.Mediator.AspNet.SourceGenerators.dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false" />
    </ItemGroup>
</Project>
